AOEpeople/aoe_technology_radar

common/radar.js
js/components/Header.js
js/components/Icon.js
js/components/PageOverview.js
tasks/assets.js
tasks/build.js
tasks/watch.js

There are some unused imports. This PR removes them.

Remove unused imports

---

.gitignore
radar/2019-11-01/beyondcorp.md
radar/2019-11-01/falco.md
radar/2019-11-01/sonarqube.md
radar/2019-11-01/stride-threat-modeling.md

Adding TechRadar items for BeyondCorp, Falco, SonarQube and STRIDE ThreatModeling to the 2019 AOE TechRadar.

adding BeyondCorp, Falco, SonarQube and STRIDE

---

common/config.js
js/components/QuadrantSection.js

feat: option to show empty rings

---

package.json
src/components/PageHelp/PageHelp.tsx
yarn.lock

allow to customize description content by sanitizing it's content
closes #102

feat: sanitize descriptions on help page

---

README.md
config_example.json
dist_scripts/scripts/createStaticFiles.js
dist_scripts/scripts/generateJson/radar.js
public/config.json
scripts/createStaticFiles.ts
scripts/generateJson/radar.ts
src/components/App.tsx
src/components/Badge/Badge.tsx
src/components/PageIndex/PageIndex.tsx
src/components/PageItem/PageItem.tsx
src/components/PageItemMobile/PageItemMobile.tsx
src/components/PageOverview/PageOverview.tsx
src/components/PageQuadrant/PageQuadrant.tsx
src/components/QuadrantGrid/QuadrantGrid.tsx
src/components/QuadrantSection/QuadrantSection.tsx
src/components/Router.tsx
src/config.ts
src/context/MessagesContext/index.tsx
src/model.ts
yarn.lock

closes #96
author: @d-koppenhagen (sorry for messing up)
replaces #97

feat: define rings and quadrants via config file

---

README.md
src/components/Footer/Footer.tsx
src/components/PageHelp/PageHelp.tsx
src/sanitize.test.tsx
src/sanitize.ts

moved sanitize function into a separate file including some simple tests
closes #91

feat: sanitize HTML in footer

---

README.md
public/config.json
src/components/ItemRevision/ItemRevision.tsx
src/components/ItemRevisions/ItemRevisions.tsx
src/components/PageIndex/PageIndex.tsx
src/components/PageItem/PageItem.tsx
src/config.ts
src/date.test.tsx
src/date.ts

feat: allow to use custom date output formats

---

scripts/generateJson/radar.ts

fix: use correct default flag type

---

README.md
public/config.json
src/components/EditButton/EditButton.tsx
src/components/EditButton/editButton.scss
src/components/PageItem/PageItem.tsx
src/components/PageItem/item-page.scss
src/components/PageItemMobile/PageItemMobile.tsx
src/config.ts

closes #115
this is a first poposal

feat: provide edit button to jump directly to the item in a repo

---

src/components/PageOverview/PageOverview.tsx

fix(search): do not filter "adopt" by default

---

.husky/pre-commit
dist_scripts/scripts/buildRadar.js
scripts/buildRadar.ts

fix(build): export REACT_APP variables during build

---

dist_scripts/scripts/generateJson.js
scripts/generateJson.ts

fix(build): check if radar folder exists

---

package-lock.json
package.json

https://stackoverflow.com/questions/71282206/github-dependabot-alert-inefficient-regular-expression-complexity-in-nth-check
Not sure if this is correctly used by users of this package...

fix(nth-check): remove vulnerability by overriding @svgr/webpack

---

package-lock.json
src/components/Chart/QuadrantRings.tsx
src/components/Chart/RadarChart.tsx

fix(radar): angle arc colors

---

dist_scripts/scripts/generateJson/radar.js
dist_scripts/src/config.js
scripts/generateJson/radar.ts
src/components/App.tsx
src/config.ts

Fallback to `/` for `PUBLIC_URL`
See #270

fix(codegen): PUBLIC_URL fallback

---

dist_scripts/scripts/createStaticFiles.js
package-lock.json
package.json
scripts/createStaticFiles.ts
scripts/types.d.ts

feat: provide sitemap

---

README.md
public/index.html
public/styles.css

feat: allow/describe how to define custom styles

---

src/components/Badge/Badge.tsx
src/components/Badge/badge.scss
src/components/ItemRevision/ItemRevision.tsx
src/components/ItemRevisions/ItemRevisions.tsx
src/components/PageItem/PageItem.tsx
src/components/PageItemMobile/PageItemMobile.tsx
src/components/PageOverview/PageOverview.tsx
src/components/QuadrantSection/QuadrantSection.tsx

fix(badges): use relative coloring for badges

---

dist_scripts/scripts/createStaticFiles.js
scripts/createStaticFiles.ts

fix: include index.html in sitemap

---

dist_scripts/scripts/createStaticFiles.js
package-lock.json
package.json
scripts/createStaticFiles.ts

fix: generate static files content

---

README.md
dist_scripts/scripts/buildRadar.js
dist_scripts/scripts/createStaticFiles.js
dist_scripts/src/config.js
package-lock.json
public/index.html
scripts/buildRadar.ts
scripts/createStaticFiles.ts
src/components/PageIndex/PageIndex.tsx
src/components/SetTitle.tsx
src/config.ts

feat: allow to define title format

---

README.md
data/config.default.json
src/app/sitemap.ts
src/lib/data.ts
tsconfig.json

feat: add sitemap.xml

---

README.md
data/config.default.json
src/lib/config.ts
src/lib/data.ts
src/pages/overview.tsx

feat: add configuration options for fuse

---

README.md
bin/techradar.js
scripts/buildData.ts
scripts/errorHandler.ts

related issue: #467 
- adds an optional build argument to build:data --strict, that breaks the breaks the build process on encountering an error
- formats the error output on build:data and colorizes it, if the terminal supports color output

feat: add strict mode for data building
